### ISSUE TITLE
각자 제안서를 수정하여 올려봅시다

### ISSUE THREAD

**Issue by DevKang** [DevKang/dgu-3d-script-docs#1]
프로젝트의 reports 폴더를 확인하면 개인 혹은 팀 이름으로 폴더가 있습니다.

그 안에 있는 README.md 파일을 본인이 최종 프로젝트로 개발할 게임에 대한 제안서로 작성하시면 되겠습니다.

**Comment by kang-karu-lab** [comment]
#2 로 추가

**Comment by DevKang** [comment]
이렇게 Pull Request 이후에 이 댓글 에디터 상단 우측 두번째 아이콘(별 모양이 그려진 책갈피 아이콘)을 통해서 Pull Request를 링크 걸어주시면 됩니다~! :)
[이 링크](https://imasoftwareengineer.tistory.com/5)를 참조하셔서 해보세요~!

**Comment by DevKang** [comment]
오타가 있어서 수정했습니다. PR #3 참조해주세요

**Comment by Kympy** [comment]
팀 이름 추가했습니다. PR #5 참조해주세요.

**Comment by zi0808** [comment]
13 김용현 [ 팀명 아레나(Arena) ]
https://github.com/iCodingDog/dgu-3d-script-docs/pull/1

**Comment by zi0808** [comment]
예전에 pull 요청한곳이 fork 연습으로 만든것인지 제가 잘못 요청했나보네요.
여튼 13 김용현, 개인작업 합니다.

pull request : https://github.com/DevKang/dgu-3d-script-docs/pull/7

**Comment by barobon** [comment]
#12 로 추가하였습니다

**Comment by godfish13** [comment]
#18 로 추가하였습니다.

**Comment by KWONTAEDOO** [comment]
#19 로 추가하였습니다.

**Comment by screat100** [comment]
#22 로 추가하였습니다.

**Comment by gw3285** [comment]
#24 로 추가하였습니다.

**Comment by Sohee97** [comment]
#25 로 추가하였습니다.

**Comment by ghost** [comment]
#25 로 추가하였습니다.

**Comment by yes99** [comment]
#26 로 추가하였습니다

**Comment by Jongmin18** [comment]
#28 게임 제안서 최종 수정하였습니다.

**Comment by joepj666** [comment]
#21 로 추가하였습니다
